import React from 'react';
import Header from './components/Header';
import Footer from './components/Footer';
import ConceptSection from './components/ConceptSection';
import FormulaCard from './components/FormulaCard';
import Placeholder from './components/Placeholder';
import { InlineMath, BlockMath } from 'react-katex';
import { DeepDiveButton } from './components/DeepDive';
import CoastlineMeasurement from './components/visualizations/CoastlineMeasurement';
import ComplexPlaneExplorer from './components/visualizations/ComplexPlaneExplorer';
import JuliaSetGenerator from './components/visualizations/JuliaSetGenerator';
import KochCurve from './components/visualizations/KochCurve';

function App() {
  return (
    <>
      <Header />
      
      {/* ═══ HERO ═══ */}
      <section id="intro" className="min-h-screen flex-center container-wide fade-in" style={{ textAlign: 'center' }}>
        <div style={{ padding: '3rem', border: '4px solid var(--accent-neon)', background: 'rgba(3,7,18,0.5)', backdropFilter: 'blur(10px)', boxShadow: '16px 16px 0px rgba(34,211,238,0.2)', marginBottom: '3rem' }}>
          <h1 style={{ fontSize: 'clamp(3rem, 8vw, 6rem)', color: 'var(--text-main)', marginBottom: '0.5rem', textShadow: '4px 4px 0px rgba(34,211,238,0.4)' }}>
            FRACTAL<br/>FORGE_
          </h1>
        </div>
        <p style={{ fontSize: '1.3rem', color: 'var(--text-dim)', maxWidth: '700px', marginBottom: '2rem', lineHeight: '1.8' }}>
          Fractals are structures created by repeating simple rules. They can look complex, but the rules behind them are often surprisingly basic. This website turns those rules into interactive experiences — so you don't just read about fractals, you <strong style={{ color: 'var(--accent-neon)' }}>explore</strong> them.
        </p>
        <a href="#module-1" className="btn-tech">BEGIN_EXPLORATION</a>
      </section>

      {/* ═══ 1. ITERATION & SIERPINSKI ═══ */}
      <ConceptSection id="module-1" index={1} title="Iteration" subtitle="// REPEATED RULES → COMPLEX STRUCTURES"
        content={<>
          <p>
            A <strong>fractal</strong> is a structure generated by repeatedly applying a simple rule. This process is called <strong>iteration</strong> — repeating the same operation again and again.
          </p>
          <p>
            At first, the rule looks simple. But after many repetitions, the result becomes highly detailed and complex. This is one of the core ideas behind fractals: <span className="highlight">a simple repeated rule creates a complex structure.</span>
          </p>
          <div className="callout">
            <strong>Sierpinski triangle:</strong> Start with one equilateral triangle. Mark the midpoints of each side. Connect them — this divides the triangle into four smaller ones. Remove the center triangle. Repeat on each remaining triangle. The result approaches the famous Sierpinski triangle.
          </div>
          <p>
            The strange thing: the rule is trivial, but the final structure has infinite detail and perfect self-similarity — zoom in and you see the same pattern at every scale.
          </p>
        </>}
        viz={<Placeholder title="Sierpinski Animation" type="viz" />}
        quiz={<Placeholder title="Iteration Quiz" type="quiz" />}
      />

      {/* ═══ 2. GEOMETRIC vs FORMULA-BASED ═══ */}
      <ConceptSection id="module-2" index={2} title="Two Types" subtitle="// GEOMETRIC vs FORMULA-BASED FRACTALS"
        content={<>
          <p>
            The Sierpinski triangle is a <strong>geometric fractal</strong> — created by directly modifying a shape using a repeated construction rule (divide, remove, copy, replace).
          </p>
          <p>
            But geometric construction isn't the only path. <strong>Formula-based fractals</strong> start with a number, plug it into a formula, and feed the result back in. After many iterations, we observe behavior: does the value settle? Escape? Spiral? The fractal appears when we color points based on that behavior.
          </p>
          <div className="compare-row">
            <div className="compare-card">
              <h4>GEOMETRIC</h4>
              <p>Rule acts directly on a <strong>shape</strong>. Structure visible immediately.</p>
            </div>
            <div className="compare-card">
              <h4>FORMULA-BASED</h4>
              <p>Rule acts on <strong>numbers</strong>. Shape appears after visualizing behavior.</p>
            </div>
          </div>
          <p>
            Fractal Forge covers both sides: geometric fractals (Sierpinski, Koch) and formula-based fractals (Julia, Mandelbrot, Newton).
          </p>
        </>}
        viz={<Placeholder title="Side-by-Side Comparison" type="viz" />}
        quiz={<Placeholder title="Classification Quiz" type="quiz" />}
      />

      {/* ═══ 3. KOCH SNOWFLAKE ═══ */}
      <ConceptSection id="geometric" index={3} title="Koch Snowflake" subtitle="// INFINITE PERIMETER, FINITE AREA"
        content={<>
          <p>
            The Koch snowflake starts as an equilateral triangle. For every side: divide into three equal parts, remove the middle third, replace it with two sides of a smaller outward triangle. Every straight segment becomes four smaller segments. Repeat.
          </p>
          <p>
            This creates an unusual mathematical property: <span className="highlight">infinite perimeter enclosing a finite area.</span> The boundary keeps getting longer, but the snowflake still fits inside a limited region.
          </p>
          <FormulaCard 
            formula="N_n = 3 \times 4^n"
            description="Number of sides at iteration n. Each old side → 4 new sides."
          />
          <FormulaCard 
            formula="l_n = \frac{s}{3^n}"
            description="Length of each side. Divided by 3 at every iteration."
          />
          <FormulaCard 
            formula="P_n = 3s\left(\frac{4}{3}\right)^n \;\longrightarrow\; \infty"
            description="Perimeter = sides × length. Since 4/3 > 1, perimeter → infinity as n → ∞."
          />
          <DeepDiveButton label="Coastline Paradox">
            <p>
              The <strong>coastline paradox</strong> reveals that the measured length of a coastline depends on the scale of measurement. Take Jordan's coastline along the <strong>Gulf of Aqaba</strong> — officially listed at about 26 km. But that number depends entirely on how you measure it.
            </p>
            <p>
              Use a 5 km ruler and you get one number — the ruler skips over rocky inlets and small bays. Switch to a 1 km ruler and the measured length increases, because now you trace around features the larger ruler missed. Use a 100 m ruler and it grows again — capturing the jagged edges of every rocky outcrop along Aqaba's shore.
            </p>
            <p>
              Reduce the ruler further — 10 m, 1 m — and the measured length keeps growing. In theory, as the measurement scale approaches zero, the coastline length approaches infinity.
            </p>
            <p>
              Mathematician <strong>Benoit Mandelbrot</strong> showed that this happens because coastlines have fractal-like properties. They are not smooth curves — they have roughness at every scale. The Koch snowflake is the idealized mathematical version: a shape where this process is carried to its logical extreme.
            </p>
            <FormulaCard
              formula="L(\varepsilon) = N(\varepsilon) \times \varepsilon"
              description="Measured length L depends on ruler size ε. Smaller ε → more segments N → longer L."
            />
            <p>
              Below, you can try this yourself: measure Jordan's Aqaba coastline with different ruler sizes and watch the <span className="highlight">measured length change as the ruler shrinks.</span>
            </p>
            <CoastlineMeasurement />
          </DeepDiveButton>
        </>}
        viz={<KochCurve />}
        quiz={<Placeholder title="Koch Quiz" type="quiz" />}
      />

      {/* ═══ 4. FRACTAL DIMENSION ═══ */}
      <ConceptSection id="dimension" index={4} title="Fractal Dimension" subtitle="// BETWEEN A LINE AND A PLANE"
        content={<>
          <p>
            Normal geometry: a line is 1D, a square is 2D, a cube is 3D. But the Koch curve doesn't fit neatly — it's more complex than a line, yet doesn't fill a plane. Its dimension is <strong>between 1 and 2.</strong>
          </p>
          <p>
            Fractal dimension doesn't mean a strange physical axis. It measures <span className="highlight">how the pattern fills space as you zoom in.</span>
          </p>
          <FormulaCard 
            formula="D = \frac{\log(N)}{\log(1/r)}"
            description="N = number of self-similar copies, r = scale factor of each copy."
          />
          <div className="compare-row">
            <div className="compare-card">
              <h4>LINE → D = 1</h4>
              <p>2 copies, r = 1/2<br/><InlineMath math="2 = 2^1" /></p>
            </div>
            <div className="compare-card">
              <h4>SQUARE → D = 2</h4>
              <p>4 copies, r = 1/2<br/><InlineMath math="4 = 2^2" /></p>
            </div>
          </div>
          <p className="mt-4">
            Koch curve: <InlineMath math="N = 4" /> copies, each at scale <InlineMath math="r = 1/3" />. So <InlineMath math="D = \log(4)/\log(3) \approx 1.262" /> — more complex than a line, less than a filled area. The boundary is fractal; the filled region inside remains 2D.
          </p>
        </>}
        viz={<Placeholder title="Dimension Comparison Tool" type="viz" />}
        quiz={<Placeholder title="Dimension Quiz" type="quiz" />}
      />

      {/* ═══ 5. COMPLEX PLANE ═══ */}
      <ConceptSection id="complex" index={5} title="Complex Plane" subtitle="// THE CANVAS FOR FORMULA-BASED FRACTALS"
        content={<>
          <p>
            To understand formula-based fractals, we need the <strong>complex plane</strong>. A complex number has a real part and an imaginary part:
          </p>
          <FormulaCard 
            formula="z = a + bi \quad\text{where}\quad i^2 = -1"
            description="a = real part (horizontal axis), b = imaginary part (vertical axis)."
          />
          <p>
            Each complex number becomes a point on a 2D plane. This is powerful for fractals because <span className="highlight">each pixel on screen can represent one complex number.</span> Apply a formula repeatedly to that number, observe the behavior, color the pixel accordingly. The image emerges from invisible numerical behavior.
          </p>
          <div className="callout">
            <strong>Squaring a Complex Number:</strong> Squaring doubles the angle and squares the modulus. <strong>Drag the blue point</strong>: inside the unit circle, <InlineMath math="z^2" /> collapses toward the origin; outside, it shoots away. The unit circle is the boundary between collapse and escape — and the dashed circle at <InlineMath math="r=2" /> is the escape radius every Julia/Mandelbrot calculation uses. Click <strong>"Keep going →"</strong> to iterate <InlineMath math="z \to z^2" /> repeatedly and see whether the orbit stays bounded or escapes.
          </div>
          <div className="callout" style={{ borderLeftColor: 'var(--accent-neon)', marginTop: '1rem' }}>
            <strong>Next stage:</strong> So far you've been squaring <InlineMath math="z" /> repeatedly. In the next stage we add one more thing: <InlineMath math="z \to z^2 + c" />. That small change — adding a fixed complex number <InlineMath math="c" /> — is what creates the <strong>Julia set</strong>. Try it.
          </div>
        </>}
        viz={<ComplexPlaneExplorer />}
        quiz={<Placeholder title="Complex Numbers Quiz" type="quiz" />}
      />

      {/* ═══ 6. JULIA SET ═══ */}
      <ConceptSection id="julia" index={6} title="Julia Set" subtitle="// ONE FORMULA, INFINITE WORLDS"
        content={<>
          <p>
            The Julia set uses a repeated formula. Pick a fixed constant <InlineMath math="c" />, then test many different starting values of <InlineMath math="z" /> (each pixel = one starting value):
          </p>
          <FormulaCard 
            formula="z_{n+1} = z_n^2 + c"
            description="c is fixed. Each pixel = a different starting z. Iterate and observe."
          />
          <p>
            After many iterations: if the values stay bounded, the point belongs to the filled Julia set. If they escape to infinity, the point is outside. Color points by how quickly they escape — this is <strong>escape-time coloring.</strong>
          </p>
          <p>
            The fascinating part: <span className="highlight">a small change in <InlineMath math="c" /> creates a completely different Julia set.</span> One value produces a connected shape. Another produces scattered dust. Another produces spirals or branch-like structures. The constant <InlineMath math="c" /> controls the "personality" of the fractal.
          </p>
          <div className="callout">
            <strong>Try it below:</strong> Drag the green <InlineMath math="c" /> point (or use the sliders) — every move shifts the offset added after squaring. Drag the blue <InlineMath math="z_0" /> to pick a starting point and click <strong>Run orbit</strong> to watch its trajectory step by step. Then click <strong>Generate Julia set</strong> to test every pixel at once: bounded points form the colored set, escaping points are colored by <em>how fast</em> they leave. Hover any pixel to preview that point's orbit.
          </div>
          <div className="callout" style={{ borderLeftColor: 'var(--accent-neon)', marginTop: '1rem' }}>
            <strong>Next stage:</strong> You've seen that different values of <InlineMath math="c" /> create different Julia sets — some are connected blobs, some are scattered dust. Is there a pattern to <em>which</em> <InlineMath math="c" /> values produce which kind of shape? That's the <strong>Mandelbrot set</strong>.
          </div>
        </>}
        viz={<JuliaSetGenerator />}
        quiz={<Placeholder title="Julia Set Quiz" type="quiz" />}
      />

      {/* ═══ 7. MANDELBROT SET ═══ */}
      <ConceptSection id="mandelbrot" index={7} title="Mandelbrot Set" subtitle="// A MAP OF POSSIBLE BEHAVIORS"
        content={<>
          <p>
            Same formula as Julia — but the roles flip. We always start with <InlineMath math="z_0 = 0" /> and let <InlineMath math="c" /> change. Each pixel represents a different value of <InlineMath math="c" />.
          </p>
          <FormulaCard 
            formula="z_{n+1} = z_n^2 + c \quad (z_0 = 0)"
            description="If the sequence stays bounded → c belongs to the Mandelbrot set."
          />
          <p>
            The Mandelbrot set is famous for its boundary: <span className="highlight">no matter how far you zoom, new structures keep appearing.</span> Some parts look like the whole set. Others reveal entirely new patterns.
          </p>
          <p>
            But it's more than a beautiful image. It's a <strong>map of possible behaviors</strong> — each point represents a value of <InlineMath math="c" />, which can generate a unique Julia set. The Mandelbrot set is a map of Julia sets.
          </p>
        </>}
        viz={<Placeholder title="Mandelbrot Explorer" type="viz" />}
        quiz={<Placeholder title="Mandelbrot Quiz" type="quiz" />}
      />

      {/* ═══ 8. THE CONNECTION ═══ */}
      <ConceptSection id="relationship" index={8} title="The Grand Connection" subtitle="// MANDELBROT = CONTROL MAP. JULIA = RESULT."
        content={<>
          <p>
            Julia and Mandelbrot use the same formula but ask different questions:
          </p>
          <div className="compare-row">
            <div className="compare-card">
              <h4>JULIA SET</h4>
              <p><InlineMath math="c" /> fixed, <InlineMath math="z" /> changes.<br/>Each pixel = starting <InlineMath math="z" />.<br/>"One world from one <InlineMath math="c" />."</p>
            </div>
            <div className="compare-card">
              <h4>MANDELBROT SET</h4>
              <p><InlineMath math="z_0 = 0" /> fixed, <InlineMath math="c" /> changes.<br/>Each pixel = a value of <InlineMath math="c" />.<br/>"A map of possible worlds."</p>
            </div>
          </div>
          <div className="callout">
            <strong>Key insight:</strong> The Mandelbrot set is the control map. The Julia set is the result. Click a point inside the Mandelbrot set → generates a connected Julia set. Click outside → the Julia set becomes disconnected, dust-like. One parameter changes an entire mathematical world.
          </div>
        </>}
        viz={<Placeholder title="Mandelbrot-to-Julia" type="viz" />}
        quiz={<Placeholder title="Connection Quiz" type="quiz" />}
      />

      {/* ═══ 9. NEWTON FRACTAL ═══ */}
      <ConceptSection id="newton" index={9} title="Newton's Fractal" subtitle="// WHEN EQUATION-SOLVING CREATES ART"
        content={<>
          <p>
            Newton's method is normally used to approximate roots of an equation — values where <InlineMath math="f(x) = 0" />. Start with an initial guess, then improve it step by step:
          </p>
          <FormulaCard 
            formula="z_{n+1} = z_n - \frac{f(z_n)}{f'(z_n)}"
            description="Each iteration improves the guess toward a root."
          />
          <p>
            When we apply this to <strong>every point on the complex plane</strong> as a starting guess, something unexpected happens. Each point eventually converges to one of the function's roots. Color each point by which root it reaches — and a fractal appears.
          </p>
          <p>
            The surprise: <span className="highlight">two starting points extremely close together may converge to different roots,</span> creating a complicated fractal boundary between colored regions.
          </p>
          <div className="callout">
            <strong>Example:</strong> For <InlineMath math="f(z) = z^3 - 1" />, there are three roots. Three colors. The boundaries between them form an infinitely detailed fractal. Newton's fractal connects algebra, calculus, complex numbers, iteration, and visualization in one image.
          </div>
        </>}
        viz={<Placeholder title="Newton Fractal Visualizer" type="viz" />}
        quiz={<Placeholder title="Newton Quiz" type="quiz" />}
      />

      {/* ═══ 10. CHALLENGE MODE ═══ */}
      <section id="challenge" className="container-wide py-20 min-h-screen flex-center fade-in" style={{ textAlign: 'center' }}>
        <div style={{ marginBottom: '3rem', borderBottom: '4px solid var(--accent-neon)', paddingBottom: '2rem', display: 'inline-block' }}>
          <span className="sec-index">SEC.10</span>
          <h2 style={{ fontSize: 'clamp(2rem, 5vw, 4rem)', color: 'var(--text-main)', margin: 0 }}>MASTER_CHALLENGE</h2>
        </div>
        <p style={{ color: 'var(--text-dim)', maxWidth: '700px', margin: '0 auto 1.5rem auto', fontSize: '1.15rem', lineHeight: '1.7' }}>
          The explanation teaches the idea. The visualization shows it. <strong style={{ color: 'var(--accent-neon)' }}>The challenge makes you apply it.</strong>
        </p>
        <p style={{ color: 'var(--text-muted)', maxWidth: '600px', margin: '0 auto 3rem auto', fontSize: '1rem', fontFamily: 'var(--font-display)' }}>
          INTERACT WITH FRACTAL RULES. PARAMETERS. ITERATIONS. PATTERNS.
        </p>
        <div style={{ width: '100%', maxWidth: '900px' }}>
          <Placeholder title="Mastery Challenge Board" type="quiz" />
        </div>
      </section>

      <Footer />
    </>
  );
}

export default App;
